//auth actions
export const AUTH_START ='AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL= 'AUTH_FAIL'
export const AUTH_LOGOUT ='AUTH_LOGOUT'


//post actions
export const FETCH_POSTS_START ='FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS ='FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL ='FETCH_POSTS_FAIL'

export const POST_START ='POST_START'
export const POST_SUCCESS ='POST_SUCCESS'
export const POST_FAIL ='POST_FAIL'

export const DELETE_POST_START ='DELETE_POST_START'
export const DELETE_POST_SUCCESS ='DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL ='DELETE_POST_FAIL'

export const LIKE_POST_START ='LIKE_POST_START'
export const LIKE_POST_SUCCESS ='LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL ='LIKE_POST_FAIL'

export const UNLIKE_POST_START ='UNLIKE_POST_START'
export const UNLIKE_POST_SUCCESS ='UNLIKE_POST_SUCCESS'
export const UNLIKE_POST_FAIL ='UNLIKE_POST_FAIL'

export const COMMENT_START ='COMMENT_START'
export const COMMENT_SUCCESS ='COMMENT_SUCCESS'
export const COMMENT_FAIL ='COMMENT_FAIL'

export const DELETE_COMMENT_START ='DELETE_COMMENT_START'
export const DELETE_COMMENT_SUCCESS ='DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL ='DELETE_COMMENT_FAIL'


//user actions
export const FETCH_USERINFO_START ='FETCH_USERINFO_START'
export const FETCH_USERINFO_SUCCESS ='FETCH_USERINFO_SUCCESS'
export const FETCH_USERINFO_FAIL ='FETCH_USERINFO_FAIL'

export const FOLLOW_START ='FOLLOW_START'
export const FOLLOW_SUCCESS ='FOLLOW_SUCCESS'
export const FOLLOW_FAIL ='FOLLOW_FAIL'

export const UNFOLLOW_START ='UNFOLLOW_START'
export const UNFOLLOW_SUCCESS ='UNFOLLOW_SUCCESS'
export const UNFOLLOW_FAIL ='UNFOLLOW_FAIL'

export const SAVE_SETTINGS_CHANGES_START ='SAVE_SETTINGS_CHANGES_START'
export const SAVE_SETTINGS_CHANGES_SUCCESS ='SAVE_SETTINGS_CHANGES_SUCCESS'
export const SAVE_SETTINGS_CHANGES_FAIL ='SAVE_SETTINGS_CHANGES_FAIL'