//auth actions
export const AUTH_START ='AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL= 'AUTH_FAIL'
export const AUTH_LOGOUT ='AUTH_LOGOUT'


// post actions
export const FETCH_POSTS_START ='FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS ='FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILED ='FETCH_POSTS_FAILED'

export const POST_START ='POST_START'
export const POST_SUCCESSFUL ='POST_SUCCESSFUL'
export const POST_FAILED ='POST_FAILED'

export const DELETE_POST_START ='DELETE_POST_START'
export const DELETE_POST_SUCCESSFUL ='DELETE_POST_SUCCESSFUL'
export const DELETE_POST_FAILED ='DELETE_POST_FAILED'

export const LIKEDISLIKE_POST_START ='LIKEDISLIKE_POST_START'
export const LIKEDISLIKE_POST_SUCCESSFUL ='LIKEDISLIKE_POST_SUCCESSFUL'
export const LIKEDISLIKE_POST_FAILED ='LIKEDISLIKE_POST_FAILED'

export const COMMENT_START ='COMMENT_START'
export const COMMENT_SUCCESSFUL ='COMMENT_SUCCESSFUL'
export const COMMENT_FAILED ='COMMENT_FAILED'

export const DELETE_COMMENT_START ='DELETE_COMMENT_START'
export const DELETE_COMMENT_SUCCESSFUL ='DELETE_COMMENT_SUCCESSFUL'
export const DELETE_COMMENT_FAILED ='DELETE_COMMENT_FAILED'


// user actions
export const FETCH_USERINFO_START ='FETCH_USERINFO_START'
export const FETCH_USERINFO_SUCCESS ='FETCH_USERINFO_SUCCESS'
export const FETCH_USERINFO_FAILED ='FETCH_USERINFO_FAIL'

export const FOLLOW_START ='FOLLOW_START'
export const FOLLOW_SUCCESS ='FOLLOW_SUCCESS'
export const FOLLOW_FAILED ='FOLLOW_FAIL'

export const UNFOLLOW_START ='UNFOLLOW_START'
export const UNFOLLOW_SUCCESS ='UNFOLLOW_SUCCESS'
export const UNFOLLOW_FAIL ='UNFOLLOW_FAIL'

export const SAVE_SETTINGS_CHANGES_START ='SAVE_SETTINGS_CHANGES_START'
export const SAVE_SETTINGS_CHANGES_SUCCESS ='SAVE_SETTINGS_CHANGES_SUCCESS'
export const SAVE_SETTINGS_CHANGES_FAIL ='SAVE_SETTINGS_CHANGES_FAIL'