export const AUTH_START ='AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL= 'AUTH_FAIL'
export const AUTH_LOGOUT ='AUTH_LOGOUT'

// export const BUDGET_CALCULATE_SUCCESS = 'BUDGET_CALCULATE_SUCCESS'

// export const ADD_SUCCESSFUL = 'ADD_SUCCESSFUL'
// export const ADD_START ='ADD_START'
// export const ADD_FAILED ='ADD_FAILED'

// export const EDIT_SUCCESSFUL = 'EDIT_SUCCESSFUL'
// export const EDIT_START ='EDIT_START'
// export const EDIT_FAILED ='EDIT_FAILED'

// export const DELETE_SUCCESSFUL = 'DELETE_SUCCESSFUL'
// export const DELETE_START ='DELETE_START'
// export const DELETE_FAILED ='DELETE_FAILED'

// export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
// export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED'
// export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START'


// export const FETCH_BUDGETINFO_SUCCESS = 'FETCH_BUDGETINFO_SUCCESS'
// export const FETCH_BUDGETINFO_START = 'FETCH_BUDGETINFO_START'
// export const FETCH_BUDGETINFO_FAILED = 'FETCH_BUDGETINFO_FAILED'

// export const SAVE_SETTINGS_CHANGES_SUCCESS = 'SAVE_SETTINGS_CHANGES_SUCCESS'
// export const SAVE_SETTINGS_CHANGES_START = 'SAVE_SETTINGS_CHANGES_START'
// export const SAVE_SETTINGS_CHANGES_FAILED = 'SAVE_SETTINGS_CHANGES_FAILED'